### PR TITLE
Fixed accessibility issues mentioned in issue #48

### PR DESCRIPTION
**Pull request by dance2die**
## 📝 Description

This is a first PR for accessibility (a11y) issues mentioned in #48.
Would you let me know if this PR does not meet the direction of the site?

## 📈 Progress

Adding `alt` attributes on images took care of two a11y issues

- [x] Images must have alternate text (4 issues)
- [x] Links must have discernible text (3 issues)
- [x] Zooming and scaling must not be disabled (1 issues)
- [x] Document must have one main landmark (1 issue)
- [x] All page content must be contained by landmarks (1 issue)

### CODE REVIEW

**Comment by dance2die** [comment]
All accessibility issues has been fixed.

⚠ "Elements must have sufficient color contrast" hasn't been touched as it'd require changing the theme color.

fixed

**Comment by dance2die** [comment]
Axe test run on Netlify preview deployment.

Netlify preview deployment check with Axe

**Review by NickFoden — APPROVED** [review]
Heck yeah !

**Comment by dance2die** [comment]
Oh yeah, @NickFoden :smile: :fist_oncoming:

**Pull request merged**
